[package]
name = "hot-latex"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
notify = "5.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
colored = "3.0.0"
crossterm = "0.28.1"
